typedef int s32;
typedef char s8;
typedef double f64;
typedef float f32;
typedef short int s16;
typedef long double f128;
typedef long long int s64;
typedef unsigned int u32;
typedef unsigned char u8;
typedef unsigned short int u16;
